spring:
  application:
    name: ms-c

server:
  port: 8003

logging:
  pattern:
    console: '%black(%d{ISO8601}) | %highlight(%-5level) | %X{correlationId} | %yellow(%C): %msg%n%throwable'
    file: '%d | %p | %X{correlationId} | %C{1.} | [%t] %m%n'
  logback:
    rollingpolicy:
      max-history: 90
